[status]
protocol_version = 774
version_string = "1.21.11"
echo_version = false
motd = "How many times do I have to ask who farted????"
[server]
bind = "0.0.0.0"
port = 25566
max_players = 10
buffer_size = 65536
[world]
hardcore = false
view_distance = 8
simulation_distance = 8
reduced_debug_info = false
respawn_screen = true
limited_crafting = false
seed = 0
default_gamemode = 3
debug = false
superflat = true
portal_cooldown = 300
sea_level = 64
enforce_secure_chat = false
